# Generated by Django 3.1.7 on 2021-03-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210331_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
